version: '3.4'

services:
  avaliacoes:
    image: avaliacoes
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:80
